---
- name: manage service
  hosts: all
  become: yes
  vars:
    service_name: "httpd"
  tasks:
    - name: start
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: started
      ignore_errors: yes

    - name: stop
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: stopped
      ignore_errors: yes
